2013/05/01 19:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "post".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php?r=post
---
2013/05/01 19:13:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php?r=gii
---
2013/05/01 19:13:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php?r=gii
---
2013/05/01 19:16:05 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.tblPrefix" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\YiiBase.php(220): CComponent->__set('tblPrefix', 'tbl_')
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#3 C:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#4 C:\xampp\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#5 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#6 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/blog/index.php?r=gii/model
---
2013/05/01 19:16:23 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.tblPrefix" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\YiiBase.php(220): CComponent->__set('tblPrefix', 'tbl')
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#3 C:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#4 C:\xampp\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#5 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#6 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/blog/index.php?r=gii/model
---
2013/05/01 19:19:15 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii_blog.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in C:\xampp\htdocs\blog\index.php (13)
2013/05/01 19:20:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "post".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php?r=post
---
2013/05/01 19:20:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "post".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/blog/index.php?r=post
---
2013/05/01 19:22:54 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "validatePassword".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:265
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(225): CComponent->__call('validatePasswor...', Array)
#1 C:\xampp\htdocs\blog\protected\components\UserIdentity.php(26): CActiveRecord->__call('validatePasswor...', Array)
#2 C:\xampp\htdocs\blog\protected\components\UserIdentity.php(26): User->validatePassword('demo')
#3 C:\xampp\htdocs\blog\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\blog\protected\controllers\SiteController.php(94): CModel->validate()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/blog/index.php?r=site/login
HTTP_REFERER=http://localhost/blog/index.php?r=site/login
---
2013/05/01 19:23:47 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/blog/index.php?r=post/admin
HTTP_REFERER=http://localhost/blog/index.php?r=post
---
2013/05/01 19:26:12 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/blog/index.php?r=post/admin
---
2013/05/01 19:29:09 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/blog/index.php?r=post/admin
---
2013/05/01 19:30:44 [error] [php] include(normalizeTags.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:421)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(186): import()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(286): createValidator()
#2 C:\xampp\htdocs\yii\framework\base\CModel.php(260): Post->createValidators()
#3 C:\xampp\htdocs\yii\framework\base\CModel.php(303): Post->getValidators()
#4 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1237): Post->isAttributeRequired()
#5 C:\xampp\htdocs\yii\framework\web\widgets\CActiveForm.php(562): activeLabelEx()
#6 C:\xampp\htdocs\blog\protected\views\post\_form.php(19): CActiveForm->labelEx()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): PostController->renderInternal()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(869): PostController->renderFile()
#10 C:\xampp\htdocs\blog\protected\views\post\create.php(18): PostController->renderPartial()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): PostController->renderInternal()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(869): PostController->renderFile()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(782): PostController->renderPartial()
#15 C:\xampp\htdocs\blog\protected\controllers\PostController.php(79): PostController->render()
#16 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): PostController->actionCreate()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#18 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): PostController->runAction()
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#21 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): PostController->filterAccessControl()
#22 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#23 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\yii\framework\web\CController.php(265): PostController->runActionWithFilters()
#25 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): PostController->run()
#26 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#27 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#28 C:\xampp\htdocs\blog\index.php(13): CWebApplication->run()
REQUEST_URI=/blog/index.php?r=post/create
in C:\xampp\htdocs\blog\protected\views\post\_form.php (19)
in C:\xampp\htdocs\blog\protected\views\post\create.php (18)
in C:\xampp\htdocs\blog\protected\controllers\PostController.php (79)
2013/05/01 19:31:11 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/blog/index.php?r=post/admin
HTTP_REFERER=http://localhost/blog/index.php?r=post
---
2013/05/01 19:10:22 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:179
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(142): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 C:\xampp\htdocs\blog\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/blog/index.php?r=user/admin
HTTP_REFERER=http://localhost/blog/index.php?r=user/create
---
2013/05/01 19:20:41 [error] [php] include(normalizeTags.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:421)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(186): import()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(286): createValidator()
#2 C:\xampp\htdocs\yii\framework\base\CModel.php(260): Post->createValidators()
#3 C:\xampp\htdocs\yii\framework\base\CModel.php(303): Post->getValidators()
#4 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1237): Post->isAttributeRequired()
#5 C:\xampp\htdocs\yii\framework\web\widgets\CActiveForm.php(562): activeLabelEx()
#6 C:\xampp\htdocs\blog\protected\views\post\_form.php(19): CActiveForm->labelEx()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): PostController->renderInternal()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(869): PostController->renderFile()
#10 C:\xampp\htdocs\blog\protected\views\post\create.php(18): PostController->renderPartial()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): PostController->renderInternal()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(869): PostController->renderFile()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(782): PostController->renderPartial()
#15 C:\xampp\htdocs\blog\protected\controllers\PostController.php(79): PostController->render()
#16 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): PostController->actionCreate()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#18 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): PostController->runAction()
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#21 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): PostController->filterAccessControl()
#22 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#23 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\yii\framework\web\CController.php(265): PostController->runActionWithFilters()
#25 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): PostController->run()
#26 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#27 C:\xampp\htdocs\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#28 C:\xampp\htdocs\blog\index.php(13): CWebApplication->run()
REQUEST_URI=/blog/index.php?r=post/create
in C:\xampp\htdocs\blog\protected\views\post\_form.php (19)
in C:\xampp\htdocs\blog\protected\views\post\create.php (18)
in C:\xampp\htdocs\blog\protected\controllers\PostController.php (79)
